---
apiVersion: v1
kind: Service
metadata:
  name: kcount
spec:
  selector:
    app: kcount
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2112
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcount
  labels:
    app: kcount
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kcount
  template:
    metadata:
      labels:
        app: kcount
    spec:
      containers:
      - name: kcount
        image: ghcr.io/pan-net-security/kcount:latest
        resources:
          limits:
            memory: "128Mi" # 128 MiB
            cpu: "500m"     # 0.5 CPU
        args:
          - -a
          - -d
      serviceAccountName: default # CHANGEME
